version: "3"
services:
  server:
    env_file:
      - .env
    # image: cityguide-graphql
    image: ericp84/cityguideserver
    ports:
      - 5070:4000
      - 3001:3001
    volumes:
      - ./src:/app/src
  db:
    ports:
      - 5071:5432
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecret
    # volumes:
    #   - /var/lib/postgresql/data
# version: '3'

# services:
#   api:
#     # image wildbookapi
#     build: ./
#     ports:
#       - 3000:5000
#   db:
#     image: postgres
#     environment:
#       POSTGRES_PASSWORD:supersecret
