version: "3"
services:
  server:
    env_file:
      - .env
    # image: cityguide-graphql
    image: ericp84/cityguideserver:staging
    ports:
      - 5070:4000
      - 3001:3001
    volumes:
      - ./src:/app/src
  db:
    ports:
      - 5071:5432
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecret
